# docker run -d 
# -e MYSQL_ROOT_PASSWORD=password12 -e MYSQL_DATABASE=todos -e MYSQL_USER=userOne -e MYSQL_PASSWORD=password12 
# --name mysql 
# -p 8033:3306 
# mysql:5.7




# docker run -d 
# -p 8080:8080 
# --link=mysql 
# -e RDS_HOSTNAME=mysql 
# -e RDS_PORT=3306 
# deepaksama26/todo-kube-demo:0.0.1-SNAPSHOT 
version: '3.9'
services:
  todo-kube-demo:
    image: deepaksama26/todo-kube-demo:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
    environment:
      - RDS_DB_NAME=todos
      - RDS_HOSTNAME=mysql
      - RDS_PORT=3306
      - RDS_USERNAME=userone
      - RDS_PASSWORD=password12
    
  mysql: 
    image: mysql:5.7
    ports:
      - "8033:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password12
      - MYSQL_DATABASE=todos
      - MYSQL_USER=userone 
      - MYSQL_PASSWORD=password12
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
volumes:
  mysql-database-data-volume:








